[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "backend"
version = "0.1.0"
description = "Backend logic engine"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["."]
include = ["backend*"]
